### ISSUE TITLE
Esp32 Deepsleep confusion

### ISSUE THREAD

**Issue by sagar448** [maarten-pennings/CCS811#51]
Hey,

Had a couple questions, I want to deep sleep with the esp32 for about 20minutes. How would this work with this sensor? Do I just set the mode to the 60second one and then just go to sleep and not put the sensor to sleep? And then when the esp32 Wakes up it will be able to get the data? How would I restore the settings? A detailed explanation would really help! Thank you.

**Comment by maarten-pennings** [comment]
Hi, it is a bad idea to power off the ccs811. So if low power is your goal, i would indeed put the ccs811 in its lowest power mode. It should be possible to sleep the esp, and let it wake up after (a bit more) than 60s, and read the ccs811. I never tried it myself. Since the ccs is in low power, but not off, it is not necessary to retire baselines.
